version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-minor:
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        dependency-type: "development"
      github:
        patterns:
          - "*github*"
      squareup:
        patterns:
          - "*squareup*"
      jackson:
        patterns:
          - "*jackson*"
      maven-plugins:
        patterns:
          - "*org.apache.maven.plugins*"
