/** 
 * Copyright (C) 2024-2023 BonitaSoft S.A.
 * BonitaSoft, 32 rue Gustave Eiffel - 38000 Grenoble
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2.0 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.bonitasoft.web.client.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.6.0")
@JsonIgnoreProperties(value = "", // ignore manually set , it will be automatically generated by Jackson during serialization
        allowSetters = true // allows the  to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, defaultImpl = LegacyApplication.class, include = JsonTypeInfo.As.PROPERTY, property = "link", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = LegacyApplication.class, name = "false"),
        @JsonSubTypes.Type(value = ApplicationLink.class, name = "true")
})
public interface Application extends Serializable {

    public String getCreatedBy();

    public String getCreationDate();

    public String getDescription();

    public String getDisplayName();

    public String getId();

    public String getLastUpdateDate();

    public String getProfileId();

    public String getToken();

    public String getUpdatedBy();

    public String getVersion();

    public Boolean getEditable();

    public Boolean getLink();

}
