name: workflow-build

on:
  workflow_call:
    inputs:
      maven-central-publication:
        type: boolean
        default: false
    secrets:
      KSM_CONFIG:
        required: true

env:
  BONITA_LATEST_SNAPSHOT_VERSION: "11.2-SNAPSHOT"

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ vars.BONITASOFT_DOCKER_REGISTRY }}
          username: ${{ env.JFROG_USER }}
          password: ${{ env.JFROG_TOKEN }}

      - name: Compile and test project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: >
          ./mvnw -B -ntp verify sonar:sonar
          -Dsonar.scanner.force-deprecated-java-version=true
          -Dbonita.image=${{ vars.BONITASOFT_DOCKER_REGISTRY }}/${{ vars.DOCKER_SNAPSHOTS_REPOSITORY }}/bonita-community:${{ env.BONITA_LATEST_SNAPSHOT_VERSION }}

       # Build and Push snapshots to maven central
      - name: Deploy snapshots to Maven central
        if: ${{ inputs.maven-central-publication }}
        run: ./mvnw -B -ntp deploy -DskipTests=true -Pdeploy

  test-supported-versions:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # Use Bonita public images when possible to test the supported versions
        bonita-image:
          - 'bonita:9.0.0'
          # 10.0.0 and 10.1.0 are not available publicly
          - '${{ vars.BONITASOFT_DOCKER_REGISTRY }}/${{ vars.DOCKER_RELEASES_REPOSITORY }}/bonita-community:10.0.0'
          - '${{ vars.BONITASOFT_DOCKER_REGISTRY }}/${{ vars.DOCKER_RELEASES_REPOSITORY }}/bonita-community:10.1.0'
          - 'bonita:10.2.0'
          # Public 10.3.0 contains a bug that prevents the tests from running successfully, switching to internal 10.3.3
          - '${{ vars.BONITASOFT_DOCKER_REGISTRY }}/${{ vars.DOCKER_RELEASES_REPOSITORY }}/bonita-community:10.3.3'
          - 'bonita:10.4.5'
          - 'bonita:11.0.0'
          - 'bonita:11.1.0'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Login to Bonita Docker registry
        if: startsWith(matrix.bonita-image, vars.BONITASOFT_DOCKER_REGISTRY)
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ vars.BONITASOFT_DOCKER_REGISTRY }}
          username: ${{ env.JFROG_USER }}
          password: ${{ env.JFROG_TOKEN }}

      - name: ${{ matrix.bonita-version }} Integration tests
        run: ./mvnw -B -ntp verify -Dbonita.image=${{ matrix.bonita-image }}
