name: workflow-build

on:
  workflow_call:
    inputs:
      maven-central-publication:
        type: boolean
        default: false
    secrets:
      KSM_CONFIG:
        required: true

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.BONITASOFT_DOCKER_REGISTRY }}
          username: ${{ env.JFROG_USER }}
          password: ${{ env.JFROG_TOKEN }}

      - name: Compile and test project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: ./mvnw -B -ntp clean verify sonar:sonar -Dsonar.scanner.force-deprecated-java-version=true -Dbonita.image=${{ vars.BONITASOFT_DOCKER_REGISTRY }}/${{ vars.DOCKER_SNAPSHOTS_REPOSITORY }}/bonita-community:10.3-SNAPSHOT

       # Build and Push snapshots to maven central
      - name: Deploy snapshots to Maven central
        if: ${{ inputs.maven-central-publication }}
        run: ./mvnw -B -ntp deploy -DskipTests=true -Pdeploy

  test-supported-versions:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        bonita-version:
          - '8.0.0'
          - '9.0.0'
          - '10.0.0'
          - '10.1.0'
          - '10.2.0'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.BONITASOFT_DOCKER_REGISTRY }}
          username: ${{ env.JFROG_USER }}
          password: ${{ env.JFROG_TOKEN }}

      - name: ${{ matrix.bonita-version }} Integration tests
        run: ./mvnw -B -ntp verify -Dbonita.image=${{ vars.BONITASOFT_DOCKER_REGISTRY }}/${{ vars.INTERNAL_DOCKER_REPOSITORY_RELEASE }}/bonita-community:${{ matrix.bonita-version }}
