name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish"
        type: string
        required: true
        default: "x.y.z"

jobs:
  build:
    name: Publication pipeline
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Publish tag
        run: ./mvnw -ntp --batch-mode deploy -Pdeploy
