name: workflow-update-spec

on:
  repository_dispatch:
    types: [new-bonita-openapi-spec-release]
  workflow_dispatch:
    inputs:
      specVersion:
        description: 'The version of the Bonita OpenAPI spec'
        required: true
        type: string
        
env:
  spec_version: ${{ github.event.client_payload.spec_version || inputs.specVersion }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Compile and test project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -ntp versions:set-property -DnewVersion=${{env.spec_version}} -Dproperty=bonita-openapi.version
          ./mvnw -ntp groovy:execute@update-spec
          ./mvnw -ntp generate-sources -Dcodegen.skip=false
          ./mvnw -ntp spotless:apply
          ./mvnw -B -ntp clean verify

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        id: create-pr
        with:
          branch: feat/update-bonita-openapi-spec
          base: develop
          commit-message: "feat(openapi): update version"
          title: "feat(openapi): update version"
          body: |
            Update Bonita OpenAPI spec with ${{env.spec_version}} version.
          